### ISSUE TITLE
Pytest required additional libraries. 

### ISSUE THREAD

**Issue by Hemanth95** [AtsushiSakai/PythonRobotics#1004]
**Describe the bug**
I cloned the code to my local machine and installed the requirements, but when i ran pytest to test the code, I got import erros for the below mentioned libraries :
1.  pyyaml
2. jinja 
3. lark-parser
4. setuptools 
5. typeguard.

And the pytest was successful after installing these. 
Is the expected behavior? 

**Desktop (please complete the following information):**
 - Python version : 3.12
 - OS version: Ubuntu 22.04

**Comment by AtsushiSakai** [comment]
@Hemanth95 How did you installed the requirements?
And could you please paste the error code?
