### ISSUE TITLE
Submitted to awesome-python

### ISSUE THREAD

**Issue by daniel-s-ingram** [AtsushiSakai/PythonRobotics#103]
Just so everyone knows, I created a pull request in awesome-python ([https://github.com/vinta/awesome-python/pull/1125](url)) to add a link to this repository!

**Comment by AtsushiSakai** [comment]
@daniel-s-ingram @jwdinius @karanchawla @araffin @AlexisTM 
Hi guys. If you have time, could you please vote for this PR to merge it. Thanks.
https://github.com/vinta/awesome-python/pull/1125

**Comment by ayan1991** [comment]
Great open source project, but is there a C++ version?
