### ISSUE TITLE
small typo on the "PythonRobotics/PathTracking/model_predictive_speed_and_steer_control"

### ISSUE THREAD

**Issue by caseypen** [AtsushiSakai/PythonRobotics#119]
In linear discrete model of C matrix, there should be a negative sign on the last item in the vector. In the code, it also misses. However, this missing does not affect the performance. It's wired.

**Comment by AtsushiSakai** [comment]
@caseypen Can you make a PR?

**Comment by caseypen** [comment]
Sure, I did it.
