### ISSUE TITLE
Real time path planning

### ISSUE THREAD

**Issue by ManuelCostanzo** [AtsushiSakai/PythonRobotics#129]
Hello, i have a question. Which of the planning algorithms of this repository recommend to use for an application that needs real-time planning ?

Thank you so much.

**Comment by AtsushiSakai** [comment]
@ManuelCostanzo Thank you for your interest.
I’m sorry I’m busy now and don’t have time to consult your question.
If you need my e-mail consultaThanktion, please consider being a patron for my oss project.
https://www.patreon.com/myenigma

Best.
