### ISSUE TITLE
Graph SLAM edge angle error term seems incorrect.

### ISSUE THREAD

**Issue by ZhenghaoFei** [AtsushiSakai/PythonRobotics#134]
Hi,

I saw you used the following equations to calculate angle error term in an edge.
```
hyaw = phi1 - phi2 + angle1 - angle2
edge.e[2, 0] = pi_2_pi(yaw2 - yaw1 - hyaw)
```
However, phi is a noise-free measurement angle from:
`def observation(xTrue, xd, u, RFID):
`
Which should not be obtained. Can you please check?

Happy Thanksgiving!

**Comment by AtsushiSakai** [comment]
@ZhenghaoFei Thank you for your comment.
