### ISSUE TITLE
EKF doc 

### ISSUE THREAD

**Issue by lyuchuny3** [AtsushiSakai/PythonRobotics#143]
Hi, 
I find a error in EKF doc:
https://pythonrobotics.readthedocs.io/en/latest/modules/localization.html#motion-model 
B[0][0] should be  `cos(\phi)dt`
B[1][0] should be `sin(\phi)dt`

your doc inverse the cos and sin.
Thanks

**Comment by AtsushiSakai** [comment]
@lyuchuny3 Thank you for your report!. I fixed it.
