### ISSUE TITLE
Reason for goal sampling in RRTstar

### ISSUE THREAD

**Issue by luym11** [AtsushiSakai/PythonRobotics#147]
The below line 118 https://github.com/AtsushiSakai/PythonRobotics/blob/7fb48a9074d2f4df701c45799d201c7db3a3eeee/PathPlanning/RRTstar/rrt_star.py#L118 is different from the original algorithm 6 in [RRT start paper](https://core.ac.uk/download/pdf/18173530.pdf). In the original `SampleFree()` method, the author is not sampling the goal at all. But as I tested, frequently sampling the goal makes the algorithm converge faster. I guess one reason could be that the line 52 shown below https://github.com/AtsushiSakai/PythonRobotics/blob/7fb48a9074d2f4df701c45799d201c7db3a3eeee/PathPlanning/RRTstar/rrt_star.py#L52 is actually steering the tree to the sampled point from `get_random_point()` in your code. And by sampling the goal more frequently you're steering the tree more to the goal point, which makes the algorithm converge easier. 

I'm wondering how you got this idea and why you did this goal sampling in the code. 

Thank you. 

Yours, 
Yimeng

**Comment by luym11** [comment]
@AtsushiSakai Thanks for your reply. Also while reading the code in 'rrt_star.py' I think I've found some inconsistency with the original paper. I'll do a pull request in recent days.

**Comment by AtsushiSakai** [comment]
@luym11 OK. Your PR is welcome!!
