### ISSUE TITLE
README: Wrong link for cloning

### ISSUE THREAD

**Issue by toolleeo** [AtsushiSakai/PythonRobotics#156]
The current version of the README, section **How to use**, reports the following instruction to clone the repo:

```
git clone https://github.com/dhiegomaga/PythonRobotics.git
```

The link points to a repo which is an outdated (at the moment) fork of the main repo.

**Comment by AtsushiSakai** [comment]
@toolleeo Oh, you are right. Thank you for your report. I fixed it.
