### ISSUE TITLE
LQR Steering only control

### ISSUE THREAD

**Issue by iljastas** [AtsushiSakai/PythonRobotics#157]
Hi Atsushi,

do you have a reference for the lqr path tracking control with the PID speed control?
Best regards,
Ilja

**Comment by AtsushiSakai** [comment]
@iljastas Hi. I'm sorry I don't have it. But It might help you: Vehicle Dynamics and Control | Rajesh Rajamani | Springer https://www.springer.com/la/book/9781461414322
