### ISSUE TITLE
LQR Steer only: Distance Error

### ISSUE THREAD

**Issue by iljastas** [AtsushiSakai/PythonRobotics#159]
Hi Atsushi,
you don't transform the distance error into the reference coordinate system. Why?
Because this is actually necessary for the error dynamic.
Your controlled kinematic model is relatively  simple without any further dynamics, so that the feedforward is doing the whole control....

**Comment by AtsushiSakai** [comment]
@iljastas Thank you for your interest.
I’m sorry I’m busy now and don’t have time to consult your question.
If you need my e-mail consultation, please consider being a patron for my oss project.
https://www.patreon.com/myenigma
