### ISSUE TITLE
rrt_with_pathsmoothing - 'range' object has no attribute 'append'

### ISSUE THREAD

**Issue by chauvinSimon** [AtsushiSakai/PythonRobotics#16]
In [\PathPlanning\RRT\rrt_with_pathsmoothing.py](https://github.com/AtsushiSakai/PythonRobotics/blob/master/PathPlanning/RRT/rrt_with_pathsmoothing.py), I get the failure 

> 'range' object has no attribute 'append'

I fixed it by converting the python3 range object to a list: in line 112 from `deg=range(0,360,5)` to `deg=list(range(0,360,5))`

**Comment by AtsushiSakai** [comment]
@chauvinSimon Thank you so much for your bug report.
I fixed it.
