### ISSUE TITLE
Stanley control and Rear wheel feedback control in Real Time

### ISSUE THREAD

**Issue by farhanmubasher** [AtsushiSakai/PythonRobotics#160]
Hi,
I've run two path tracking examples (Stanley and Rear wheel feedback) successfully, Now i want to modify anyone example into my real time data of vehicle. 

`Basically I want to move my vehicle manually in a ground and then want it to run on that path/track autonomously.`
 
Can you please help me that how can i use this path tracking algorithms on my vehicle in real time to achieve my goal.

I will appreciate your time and effort.
Thanks.

**Comment by AtsushiSakai** [comment]
@farhanmubasher Thank you for your interest.
I’m sorry I’m busy now and don’t have time to consult your question.
If you need my e-mail consultation, please consider being a patron for my oss project.
https://www.patreon.com/myenigma
