### ISSUE TITLE
Dynamic Classes for Easy Reuse of Code

### ISSUE THREAD

**Issue by akashp1997** [AtsushiSakai/PythonRobotics#165]
Hey Guys

I was wondering that the codes that have been written are all Procedural in nature, and not really user-friendly. I had a suggestion that if you were to convert these codes to Object-Oriented Classes, it would be really easy for others to use it with the same efficiency as you would in your own projects.

**Comment by AtsushiSakai** [comment]
@akashp1997 Hi. Thank you for your suggestion. I'm sorry I don't agree that. The main purpose of this repo is for beginners to understand the algorithms. I think it is not needed be object oriented.
