### ISSUE TITLE
Small typo error

### ISSUE THREAD

**Issue by BetterRobotics** [AtsushiSakai/PythonRobotics#169]
https://github.com/AtsushiSakai/PythonRobotics/blob/c1a855d649c23e5de1f15b5ca9f0ec9c4d747c1a/Localization/extended_kalman_filter/extended_kalman_filter.py#L196

Change `plt.plot(hz[:, 0], hz[:, 1], ".g")` to `plt.plot(hz[0, :], hz[1, :], ".g")`

**Comment by AtsushiSakai** [comment]
@BetterRobotics I fixed it. Thanks!!
