### ISSUE TITLE
Continuous Curvature Path Planning

### ISSUE THREAD

**Issue by rukie** [AtsushiSakai/PythonRobotics#172]
First, I want to thank you for creating such a great resource!

I thought I'd share with you a path planning technique I recently came across. "Double Continuous Curvature." It uses Euler curves rather than Bezier curves to create continuous, differentiable paths. 

Paper:
Smooth Kinematic Controller vs. Pure-Pursuit for Non-holonomic Vehicles
https://www.researchgate.net/publication/220942087_Smooth_Kinematic_Controller_vs_Pure-Pursuit_for_Non-holonomic_Vehicles

Continuous-Curvature Control of Mobile Robots with Constrained Kinematics
http://folk.ntnu.no/skoge/prost/proceedings/ifac11-proceedings/data/html/papers/2252.pdf

**Comment by AtsushiSakai** [comment]
@rukie Hi. Thank you for sharing!! Your PR about the paper is wellcome : )
