### ISSUE TITLE
Iterative Closest Point- wrong matrix operation in update_homogeneous_matrix function 

### ISSUE THREAD

**Issue by mdmufees** [AtsushiSakai/PythonRobotics#173]
1.  function naming error - its homogeneous and not homogenerous
def update_homogenerous_matrix(Hin, R, T): 

2. the return has to be 'H @ Hin' not 'Hin * H'

code Snippet from that function:

 if Hin is None:
        return H
    else:
        return Hin * H # here only element wise multiplication takes place. it has to matmul/@

Kindly update..
Thanks for the great repo..

**Comment by AtsushiSakai** [comment]
@mdmufees Thank you for reporting. I fixed it : )
