### ISSUE TITLE
appveyor test is broken

### ISSUE THREAD

**Issue by AtsushiSakai** [AtsushiSakai/PythonRobotics#174]
python setup.py imports numpy while having it as a dependency · Issue #85 · cvxgrp/scs https://github.com/cvxgrp/scs/issues/85

**Comment by jwdinius** [comment]
It looks like the travis test is using python v3.6.8, but the appveyor test is using 3.6.5.  Is it possible to make these tests use the _same_ underlying conda environment (same python version and same package versions)?  It seems like a non-trivial amount of work is going into maintaining this appveyor ci.  My thought is that maybe the workload could be made lighter by just making sure the two tests are as similar as possible.

**Comment by AtsushiSakai** [comment]
@jwdinius Thank you for your advice. That's good idea. Do you have any idea to achieve that?

**Comment by AtsushiSakai** [comment]
@jwdinius One idea is that I make travis-ci and appveyor use a same enviroment.yml. And then, I set a specific version for each library.

**Comment by AtsushiSakai** [comment]
I fixed it to pass the test which using cvxpy.
