### ISSUE TITLE
back move in pure pursuit

### ISSUE THREAD

**Issue by zhengzh** [AtsushiSakai/PythonRobotics#182]
Hi, these 2 lines of code in `pure_pursuit.py` is of no use since `sin(alpha)` equals `sin(pi-alpha)`, that is to say curvature is same whether the car move forward or backward
```python
if state.v < 0:  # back
  alpha = math.pi - alpha
```

**Comment by AtsushiSakai** [comment]
@zhengzh Oh, you are right. I remove it. Thank you again!!
