### ISSUE TITLE
LQR speed_steer_control

### ISSUE THREAD

**Issue by adiveloper** [AtsushiSakai/PythonRobotics#184]
in  lqr_speed_steer_control.py

in the calculate_steering angle() function:
    ff = math.atan2(L * k, 1)
what does  "1"  in the denominator represent?

**Comment by AtsushiSakai** [comment]
Thank you for your interest.
@adiveloper I’m sorry I’m busy now and don’t have time to consult your question.
If you need my e-mail consultation, please consider being a patron for my oss project or donate with paypal.
[How to Support](https://github.com/AtsushiSakai/PythonRobotics/blob/master/README.md#support)
