### ISSUE TITLE
Motion model of Potential Field

### ISSUE THREAD

**Issue by Champake** [AtsushiSakai/PythonRobotics#188]
Thanks for the dems. How did you derive the motion matrix for Potential Field Path Planning. 
Thanks
Champ

**Comment by AtsushiSakai** [comment]
I’m sorry I’m busy now and don’t have time to consult your question.
If you need my e-mail consultation, please consider being a patron for my oss project or donate with paypal.
[PythonRobotics/README\.md at master · AtsushiSakai/PythonRobotics](https://github.com/AtsushiSakai/PythonRobotics/blob/master/README.md#support)
