### ISSUE TITLE
@ in InformedRRT* code

### ISSUE THREAD

**Issue by trishantroy** [AtsushiSakai/PythonRobotics#189]
Hey,
I came across this repo while searching for InformedRRT* implementation. The code giving an error on compiling: 
```
M = a1 @ id1_t
 
SyntaxError: invalid syntax
```
The corresponding line: https://github.com/AtsushiSakai/PythonRobotics/blob/master/PathPlanning/InformedRRTStar/informed_rrt_star.py#L57

Thanks in advance.

**Comment by AtsushiSakai** [comment]
@trishantroy What is your python and numpy version? Please check README.md .

**Comment by trishantroy** [comment]
The issue was with my python environment. Thanks.
