### ISSUE TITLE
cvxpy and solve times  (model_predictive_speed_and_steer_control)

### ISSUE THREAD

**Issue by greymfm** [AtsushiSakai/PythonRobotics#209]
Hello,

Not a bug, just a note :-) - Your demos are great (ps, I sent you a little thank you) and a good starting point to learn the implementation of all kind of path tracking and planning algorithms.

I analysed your MPC demo, introduced cvxpy parameters, and split the 'problem construction' into 'problem construction (one time)' and 'parameter value assignment (control loop)' and found out that the runtime of the cvxpy solve function is still unnecessarily high. So, I posted a related 'question' here: https://github.com/cvxgrp/cvxpy/issues/762

Maybe you have an idea how to remove the solver overhead time... :)

Keep up your excellent teaching work! ;-)

Regards,
Alexander Grau

**Comment by AtsushiSakai** [comment]
@greymfm Hi. Thank you for your great information and donation!!. I know the cvxpy has a weird performance, but I don't know how to fix it. I'm excited the next version of cvxpy 1.1 : ) Thanks again.
