### ISSUE TITLE
Typo in length calculation in pure pursuit target index

### ISSUE THREAD

**Issue by EphesosX** [AtsushiSakai/PythonRobotics#212]
https://github.com/AtsushiSakai/PythonRobotics/blob/cfa97b497c23cfdb0ccffcf696cac2b315ff5128/PathPlanning/ClosedLoopRRTStar/pure_pursuit.py#L78

When calculating dy, cy should be used instead of cx.

**Comment by AtsushiSakai** [comment]
@EphesosX Thank you. Good catch!! I fixed it.
