### ISSUE TITLE
Explanation for State Lattice Planner code?

### ISSUE THREAD

**Issue by deepaktalwardt** [AtsushiSakai/PythonRobotics#219]
I am trying to understand how you implemented the state lattice planner, but I'm having trouble understanding some of the details. Where can I find explanations for what function parameters mean and how the algorithm works in general? I also don't understand how the lookup table is generated and where it came from. Please guide me in the right direction. Thanks!

**Comment by AtsushiSakai** [comment]
@deepaktalwardt HI. I added some comments for the state lattice planner code. I hope it will help you.
