### ISSUE TITLE
Paths ignoring collision(s)...

### ISSUE THREAD

**Issue by alex-ira** [AtsushiSakai/PythonRobotics#224]
Hi Atsushi

Great work! I've just started exploring and playing but am getting results as in figure below. I'd expect to get "Cannot find path". Am I missing something? 

Thanks in advance. 

Cheers
![RRT_example](https://user-images.githubusercontent.com/27619740/64930371-8d998d00-d873-11e9-8cfc-999b9886c34b.png)

**Comment by AtsushiSakai** [comment]
@alex-ira Thank you for your bug report!!. Did you use latest code? I fix a bug for it: https://github.com/AtsushiSakai/PythonRobotics/issues/223

**Comment by alex-ira** [comment]
@AtsushiSakai Yes, I did. Thanks for a quick reply!

**Comment by AtsushiSakai** [comment]
@alex-ira Currently, default path resolution is 1 meter, so the collision check might skip the obstacle. 
https://github.com/AtsushiSakai/PythonRobotics/blob/8eef2fd7bbda218d2c381c4a29a17c1f6f710591/PathPlanning/RRT/rrt.py#L35

Could you please check the same problem happen when you set the path_reolusion = 0.1?

**Comment by alex-ira** [comment]
@AtsushiSakai I think that might be the issue. I've tried path_resolution = 0.1 and got this in one of the trials:
![RRT_example2](https://user-images.githubusercontent.com/27619740/64998895-335b0380-d929-11e9-8d29-d356d5f20344.png)

**Comment by alex-ira** [comment]
@AtsushiSakai this one is with path_resolution = 0.05:
![RRT_exmaple3](https://user-images.githubusercontent.com/27619740/64999022-a82e3d80-d929-11e9-9f4e-9a1b8e413740.png)

**Comment by alex-ira** [comment]
@AtsushiSakai I just observed the same issue with RRTStar (see below; I use path_resolution = 0.1).
![RRTStar_exmaple0](https://user-images.githubusercontent.com/27619740/64999598-c5640b80-d92b-11e9-8a2f-2371684299a3.png)

**Comment by alex-ira** [comment]
@AtsushiSakai the issue seems to go away if I reduce expand_dis.

**Comment by AtsushiSakai** [comment]
@alex-ira Sorry for late reply. Could you please try the latest rrt.py code? It might from circle visualization problem. Thanks for your report.

**Comment by alex-ira** [comment]
@AtsushiSakai thanks for getting back to me. I just tried it and unfortunately there are still the same  issues (see pictures below). 

Expand_dis = 3, path_resolution = 3
![expand_dis3path_resolution3](https://user-images.githubusercontent.com/27619740/66008229-d3ec1e80-e4f8-11e9-81d6-16ce947ff3ec.png)

Expand_dis = 3, path_resolution = 1
![path_resolution1](https://user-images.githubusercontent.com/27619740/66008248-e5cdc180-e4f8-11e9-9494-8b35b30dda01.png)

Expand_dis = 3, path_resolution = 0.1
![path_resolution01](https://user-images.githubusercontent.com/27619740/66008256-ecf4cf80-e4f8-11e9-8902-5b267b00d318.png)

Expand_dis = 5, path_resolution = 0.1
![expand_dis5](https://user-images.githubusercontent.com/27619740/66008273-f7af6480-e4f8-11e9-9873-9082940b329d.png)

I've been also playing with RRTStar have the same issues. 

Thanks for your time in advance. Cheers

**Comment by alex-ira** [comment]
@AtsushiSakai might be relevant for debugging. The picture below is for RRTStar with expand_dis = 5 and path_resolution = 1:
![path_1](https://user-images.githubusercontent.com/27619740/66008929-bc626500-e4fb-11e9-82ca-6ad8a26e70e0.png)

**Comment by AtsushiSakai** [comment]
@alex-ira Oh, Obviously the last path expansion has problem. Thank you for your report. I will try to fix it.

**Comment by AtsushiSakai** [comment]
@alex-ira I fixed it. Could you please check it again?

**Comment by alex-ira** [comment]
@AtsushiSakai thanks for your work. RRT seems to be okay, however I'm finding the same issue with RRTStar. 

expand_dis = 5, path_resolution = 0.5:

![viol](https://user-images.githubusercontent.com/27619740/66089478-d155fb80-e5c2-11e9-9b60-3e5cf153d430.png)

![violationE5P05](https://user-images.githubusercontent.com/27619740/66089483-d74bdc80-e5c2-11e9-95b8-40e2420c8b2b.png)

**Comment by AtsushiSakai** [comment]
@alex-ira Are you using latest rrt_star.py? Your figure looks using old code.

<img width="592" alt="SS 2019-10-03 at 20 45 54" src="https://user-images.githubusercontent.com/3813847/66124345-13148f80-e61f-11e9-8ad3-b12dfd34feb8.png">

**Comment by alex-ira** [comment]
@AtsushiSakai no, I'm using the latesdt rrt_star.py. I just kept `"-xg"` to observe path_resolution.

**Comment by alex-ira** [comment]
@AtsushiSakai here is one with the new visuals.

![path_1](https://user-images.githubusercontent.com/27619740/66182489-a64dd380-e6b8-11e9-82ef-94d1c934e57f.png)

**Comment by AtsushiSakai** [comment]
@alex-ira Oh, thank you for your kind report. I fixed an another bug on rrt_star.py. Could you try it again? Sorry.

**Comment by alex-ira** [comment]
@AtsushiSakai thanks for all the work! It appears to be ok now.

**Comment by AtsushiSakai** [comment]
@alex-ira Thank you so much for you effort. I appreciate it.
