### ISSUE TITLE
Why is the index value calculated?

### ISSUE THREAD

**Issue by lining9717** [AtsushiSakai/PythonRobotics#237]
In Dijkstra's algorithm, the index value of the node may be repeated. 
Why is the index value calculated?
`def calc_index(self, node):
        return (node.y - self.miny) * self.xwidth + (node.x - self.minx)`

**Comment by AtsushiSakai** [comment]
@lining9717 I'm sorry, I cannot understand you question. Could you please explain for details?

**Comment by lining9717** [comment]
@AtsushiSakai I mean why you calculate the index value of each point like this
`    def calc_index(self, node):
        return (node.y - self.miny) * self.xwidth + (node.x - self.minx)`，because I think there will be some duplicate indexes.

**Comment by AtsushiSakai** [comment]
@lining9717 I'm sorry I don't understand your question... sorry.
