### ISSUE TITLE
ClosedLoopRRTStar Discrepancy

### ISSUE THREAD

**Issue by fangedward** [AtsushiSakai/PythonRobotics#250]
Hi, I am working through the implementation of `ClosedLoopRRTStar` and am unable to produce results similar to the GIF shown in the documentation. For reference, the documentation shows that `ClosedLoopRRTStar` should look like this:

![animation](https://user-images.githubusercontent.com/55596368/68533497-78266980-02de-11ea-8da4-c7bb926fc16f.gif)

However, when I run it off-the-shelf my results look much more like `RRTStarReedsShepp`. While we are using `RRTStarReedsShepp` for planning, it seems like the code is missing some core parts of the algorithm as described by https://arxiv.org/pdf/1601.06326.pdf. In particular, it doesn't keep the set of trajectory nodes obtained with the vehicle dynamics taken into account. It only uses the vehicle dynamics after `RRTStarReedsShepp` finishes planning. 

Perhaps I am mistaken, but it seems like this is a discrepancy between the paper. Regardless, thank you for all your contributions in this repository, they are extremely useful.

**Comment by AtsushiSakai** [comment]
@fangedward Hi. Thank you for your tring this project. As you said, the green line is from RRTStarReedsShepp, but after generating these path, ClosedRRTStart do a tracking simulation with pure pursuit in this code. So, the final red line is based on vehicle dynamics.
