### ISSUE TITLE
''Dynamic Window Approach'' of Path Planning in real time?

### ISSUE THREAD

**Issue by as0027111** [AtsushiSakai/PythonRobotics#252]
Hello, how to improve the ''Dynamic Window Approach'' of Path Planning in real time?
(i only need the result of prediction, not the dynamic showing)

i couldn't understand the relation of:
        self.dt = 0.1  # [s] Time tick for motion prediction
        self.predict_time = 0.5  # [s]

Or  i can use other way/function of path planning, I need velocity vector, rotation direction?

**Comment by AtsushiSakai** [comment]
Thank you for your interest.
I’m sorry I’m busy now and don’t have time to consult your question.
If you need my consultation, please consider being a sponsor.
https://github.com/sponsors/AtsushiSakai

Best
