### ISSUE TITLE
Any chance to add Dubins Curve to Hybrid A* Path Planning

### ISSUE THREAD

**Issue by ArchieGu** [AtsushiSakai/PythonRobotics#253]
HI, The hybrid_a_star is super efficient, it uses reeds_shepp curves. Is that possible that use dubins curve in this algorithm? I found it a little bit hard for me to implement it.

**Comment by AtsushiSakai** [comment]
Thank you for your interest.
I’m sorry I’m busy now and don’t have time to consult your question.
If you need my consultation, please consider being a sponsor.
https://github.com/sponsors/AtsushiSakai

Best
