### ISSUE TITLE
two questions in code 'graphSLAM_doc.ipynb'

### ISSUE THREAD

**Issue by zhchyang2004** [AtsushiSakai/PythonRobotics#264]
Hi, Atsushi, your code really benefits robotics learners. Thank you!

When I study your code in 'graphSLAM_doc.ipynb', I find two questions to be discussed with you as follows.

1.  In 'Minimal Example' ,  I think 'omegas' should be added onto the calculation. 
        b[t1] += omegas * measure_constraints[(t1,t2)]
        b[t2] -=  omegas * measure_constraints[(t1,t2)]

2. In [6] ,  'yaw1 and yaw2' has been included in tangle1 and tangle2.  So  'yaw1 and yaw2' is added twice in 'calculate the error of the virtual measurement'. 

      edge.e[2, 0] = pi_2_pi(yaw2 - yaw1 - tangle1 + tangle2)

      Should the correct code be like this?
      edge.e[2, 0] = pi_2_pi(- tangle1 + tangle2) 

      If we do so, the final result x_opt is not so good. I am confused by this issue greatly.

Thank you for your kind feedback!

**Comment by AtsushiSakai** [comment]
@zhchyang2004 Hi. I'm sorry for late reply.
@adelizer Could you please answer his question?

**Comment by adelizer** [comment]
Hi, I will look into your remarks

**Comment by AtsushiSakai** [comment]
@adelizer How about your progress?

**Comment by adelizer** [comment]
Regarding remark [1] It is correct. Indeed we need to add the measurement noise Q into the calculation. It was not showing in the results as this was a minimal example. 
I am having a problem reproducing the bad results in remark [2] but I will work on a new PR with the fix.

**Comment by AtsushiSakai** [comment]
@adelizer Thank you for check it.
>It is correct
OK I fixed it in #283
>but I will work on a new PR with the fix.
OK. great. You PR is wellcome.
