### ISSUE TITLE
Typo on KF Basics Part2

### ISSUE THREAD

**Issue by yoneken** [AtsushiSakai/PythonRobotics#281]
**Describe the bug**
$$p(z_{t} | x-\_{0:t},z\_{1:t-1},u_{1:t})=p(z_{t} | x_{t})$$
This formula in [Probabilistic Generative Laws > 2nd Law](https://render.githubusercontent.com/view/ipynb?commit=81ddb1fc3ee950f45a167764da5dfc045a3fc250&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f4174737573686953616b61692f507974686f6e526f626f746963732f383164646231666333656539353066343561313637373634646135646663303435613366633235302f4c6f63616c697a6174696f6e2f4b616c6d616e66696c7465725f6261736963735f322e6970796e62&nwo=AtsushiSakai%2FPythonRobotics&path=Localization%2FKalmanfilter_basics_2.ipynb&repository_id=54376220&repository_type=Repository#2nd-Law:) contains '-'. However, it seems to be unnecessary.

**Expected behavior**
$$p(z_{t} | x_{0:t},z_{1:t-1},u_{1:t})=p(z_{t} | x_{t})$$

**Desktop (please complete the following information):**
 - Python version : all
 - Each library version : all

**Comment by AtsushiSakai** [comment]
@yoneken Thank you for your report. I fixed it in the master branch. Please check it. If you find any other problems, new issue and PR is always welcome.
