### ISSUE TITLE
RRT star rewire() not work

### ISSUE THREAD

**Issue by sldai** [AtsushiSakai/PythonRobotics#285]
In RRTStar class, 

    def rewire(self, new_node, near_inds):
        for i in near_inds:
            near_node = self.node_list[i]
            edge_node = self.steer(new_node, near_node)
            if not edge_node:
                continue
            edge_node.cost = self.calc_new_cost(new_node, near_node)

            no_collision = self.check_collision(edge_node, self.obstacle_list)
            improved_cost = near_node.cost > edge_node.cost

            if no_collision and improved_cost:
                near_node = edge_node                    **near_node now points to a new node not in the tree**
                near_node.parent = new_node          **The parent of nodes in the tree does not actually change **
                self.propagate_cost_to_leaves(new_node)

Comment 'near_node = edge_node' can fix this bug. But I think you should check collision between near_node and new_node.

**Comment by AtsushiSakai** [comment]
@sldai Can you create a PR?

**Comment by sldai** [comment]
Yeah, I will try to do it.

**Comment by sldai** [comment]
Hi, AtsushiSakai. 
In the original RRT* paper, the vertices near the sample are checked in a range of min(expand_dist, connect_circle_dist).
In your implementation:  r = self.connect_circle_dist * math.sqrt((math.log(nnode) / nnode))
I add: r = min(r, self.expand_dis)

This guarantees the neighbor vertices are accessible from the new sample. But a problem exists that the rewire process becomes myopic, so much more samples are needed to get a optimal path. This is also shown in the RRT* paper. 

Have you ever seen any paper solving this problem?

**Comment by AtsushiSakai** [comment]
@sldai I'm sorry I don't know it..
