### ISSUE TITLE
Comments in the code!

### ISSUE THREAD

**Issue by robotics-dev-0101** [AtsushiSakai/PythonRobotics#289]
Hi
thanks for this amazing project! 

Could you please comment the code? it is not easy to try to decrypt what each symbol means!
I suppose it would be a piece of cake for the one you to comment it and it would be of great help to the community

**I am reading the SLAM algorithms and it is extremely time consuming even though I know what the algorithm does in general and sometimes it is not clear what you are doing**. I can help with some commenting when I finish reading some code and understand what it is doing, but I need time

**Comment by AtsushiSakai** [comment]
@robotics-dev-0101 Hi. I will do my best. It needs huge time.
