### ISSUE TITLE
Invalid syntax error for dynamic_window_approach

### ISSUE THREAD

**Issue by Minyanaing** [AtsushiSakai/PythonRobotics#292]
When I executing the dynamic window approach python file, an invalid syntax error has occurred as below.

> 
    File "dynamic_window_approach.py", line 173
        local_ob = np.array([local_ob @ x for x in rot])
                                      ^
     SyntaxError: invalid syntax

![Screenshot from 2020-02-12 12-50-25](https://user-images.githubusercontent.com/44282142/74304207-3a325900-4d97-11ea-9f3f-be83867431b2.png)

Is there any idea to execute the code to see the example.

Thank you for your kind feedback!

**Comment by ejalaa12** [comment]
are you using python3? 
Because the dot product operator `@` , is only available in Python 3.
If you want to use Python 2.7, you should replace every `x@y` with `x.dot(y)`

**Comment by Minyanaing** [comment]
Got it, thanks.
