### ISSUE TITLE
PathTracking/pure_pursuit Trajectory.search_target_index calculation error

### ISSUE THREAD

**Issue by markmellors** [AtsushiSakai/PythonRobotics#298]
Hi, amazing library here. I'm hoping to use the pure pursuit code in a Pi Wars robot and noticed a bug whilst trying it out. 

Once old_nearest_point_index has an initial value, the Trajectory.search_target_index method always (at least) increments the index by one, even if the current index is the correct distance away.
One way to see the impact of this is to change the step size of the points in the example, from 0.1 to 0.5 (change line 151 to `cx = np.arange(0, 50, 0.5)` ), the target point then runs away ahead of the vehicle. 
So it has no impact if the vehicle keeps moving and the waypoint density is high enough, but if the vehicle stops or its a sparsely described course, the path planning goes wrong.

**Comment by AtsushiSakai** [comment]
Thank you for reporting. I think this issue was fixed in #299, please try the latest code. BYW. If you try to use this code for your Pi Wars robot, please share a video of it. I'm happy to watch it!!
