### ISSUE TITLE
reeds_shepp_path

### ISSUE THREAD

**Issue by BlindZhou** [AtsushiSakai/PythonRobotics#314]
if the start and goal are the same pose, the rs path is not a path just contain start and goal pose.

import reeds_shepp_path_planning as rs

sx = 0
sy = 0
syaw = 0

gx = 0
gy = 0
gyaw = 0

max_curvature = 4
paths = rs.calc_paths(sx, sy, syaw, gx, gy, gyaw, max_curvature, step_size=0.1)
print(type(paths))
for path in paths:
    print(type(path))
    print(path)
    for i in range(len(path.x)):
        # print(i)
        # print(path.x[i])
        # print(path.y[i])
        # print(path.yaw[i])
        print("%d %.3f %.3f %.3f" %(i, path.x[i], path.y[i], path.yaw[i]))
    print("\n")

and output is 
 <class 'list'>
<class 'reeds_shepp_path_planning.Path'>
<reeds_shepp_path_planning.Path object at 0x7f0ca27ee978>
0 0.000 0.000 0.000
1 -0.097 0.020 -0.400
2 -0.179 0.076 -0.800
3 -0.233 0.159 -1.200
4 -0.250 0.257 -1.600
5 -0.227 0.354 -2.000
6 -0.169 0.434 -2.400
7 -0.084 0.486 -2.800
8 0.249 0.228 1.483
9 0.221 0.133 1.083
10 0.158 0.056 0.683
11 0.070 0.010 0.283
12 0.000 0.000 0.000

<class 'reeds_shepp_path_planning.Path'>
<reeds_shepp_path_planning.Path object at 0x7f0ca27ee9b0>
0 0.000 0.000 0.000
1 -0.097 -0.020 0.400
2 -0.179 -0.076 0.800
3 -0.233 -0.159 1.200
4 -0.250 -0.257 1.600
5 -0.227 -0.354 2.000
6 -0.169 -0.434 2.400
7 -0.084 -0.486 2.800
8 0.249 -0.228 -1.483
9 0.221 -0.133 -1.083
10 0.158 -0.056 -0.683
11 0.070 -0.010 -0.283
12 0.000 0.000 0.000

<class 'reeds_shepp_path_planning.Path'>
<reeds_shepp_path_planning.Path object at 0x7f0ca27ee9e8>
0 0.000 0.000 0.000
1 0.097 0.020 0.400
2 0.179 0.076 0.800
3 0.233 0.159 1.200
4 0.250 0.257 1.600
5 0.227 0.354 2.000
6 0.169 0.434 2.400
7 0.084 0.486 2.800
8 -0.015 0.500 -3.083
9 -0.111 0.474 -2.683
10 -0.189 0.413 -2.283
11 -0.238 0.327 -1.883
12 -0.249 0.228 -1.483
13 -0.221 0.133 -1.083
14 -0.158 0.056 -0.683
15 -0.070 0.010 -0.283
16 -0.000 0.000 0.000

<class 'reeds_shepp_path_planning.Path'>
<reeds_shepp_path_planning.Path object at 0x7f0ca27f2ef0>
0 0.000 0.000 0.000
1 0.097 -0.020 -0.400
2 0.179 -0.076 -0.800
3 0.233 -0.159 -1.200
4 0.250 -0.257 -1.600
5 0.227 -0.354 -2.000
6 0.169 -0.434 -2.400
7 0.084 -0.486 -2.800
8 -0.015 -0.500 3.083
9 -0.111 -0.474 2.683
10 -0.189 -0.413 2.283
11 -0.238 -0.327 1.883
12 -0.249 -0.228 1.483
13 -0.221 -0.133 1.083
14 -0.158 -0.056 0.683
15 -0.070 -0.010 0.283
16 -0.000 0.000 0.000

**Comment by AtsushiSakai** [comment]
@BlindZhou Hi. Thank you for your comments. I think that behavior is expected. Maybe the path is a circle or something which go back to the same pose. So, I think it is not a bug.
