### ISSUE TITLE
Broken Say Thanks Badge Link

### ISSUE THREAD

**Issue by mithi** [AtsushiSakai/PythonRobotics#319]
**Describe the bug**
Broken link to Saythanks URL https://saythanks.io/to/AtsushiSakai

**Expected behavior**
I expect to be redirected to a page where I can send a thank you note to the author instead 
all I see is
> Not Found The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

**Comment by AtsushiSakai** [comment]
@mithi Thank you for reporting.
