### ISSUE TITLE
CVXPY cannot be installed

### ISSUE THREAD

**Issue by willzoe** [AtsushiSakai/PythonRobotics#342]
The development environment I currently use is Ubuntu16.04+Python3.8+anaconda+pycharm.

But when I install CVXPY in anaconda to the virtual environment, it prompts that it cannot be found.

What is the recommended development environment?

**Comment by lentychang** [comment]
Hi @willzoe,  

try `conda install -c conda-forge cvxpy -n <ENV_NAME>` it should work, unless you meet some unsolved dependency.

or if conda doesn't work, you can just use pip to intall

**Comment by AtsushiSakai** [comment]
@willzoe Hi please check install doc of cvxpy: https://www.cvxpy.org/install/
If it don't work, please report it for cvxpy team.

@lentychang  Hi. Thank you for your support. I applicate it.
