### ISSUE TITLE
RRT star may be improved

### ISSUE THREAD

**Issue by rafaelrojasmiliani** [AtsushiSakai/PythonRobotics#382]
# Bug description
The RRT star algorithm  implemented [here](https://github.com/AtsushiSakai/PythonRobotics/blob/7442bdceb18b6157b733311ffcc2d544eeab901a/PathPlanning/RRTStar/rrt_star.py#L57) seems to be slightly different from the one proposed by Karaman and Frazzoli. 
In [this line](https://github.com/AtsushiSakai/PythonRobotics/blob/7442bdceb18b6157b733311ffcc2d544eeab901a/PathPlanning/RRTStar/rrt_star.py#L74) the function [choose_parent](https://github.com/AtsushiSakai/PythonRobotics/blob/7442bdceb18b6157b733311ffcc2d544eeab901a/PathPlanning/RRTStar/rrt_star.py#L95) can return None if there are no nodes within the distance r. This prevents adding new nodes to the tree also if they are no collisions in their path to the tree.

# Expected behavior
 it may be seen in Karaman, Sertac, and Emilio Frazzoli. "Sampling-based algorithms for optimal motion planning." The international journal of robotics research 30.7 (2011): 846-894, algorithm 6 line 7  that the result of steer is added to tree if they are no collisions in its straight path to the nearest point. Then its parent is computed between lines 9 and 13. If there are no nodes within the distance r, its parent results to be the nearest point.

# Note
Please, correct me if I'm wrong. Otherwise if it is possible I can fix this and provide my contribution.

# Desktop
 Ubuntu 18.04, Python3

**Comment by AtsushiSakai** [comment]
Thank you for your report. Could you please create a PR? let’s discuss in the PR.
