### ISSUE TITLE
RRT star may be improved 2

### ISSUE THREAD

**Issue by rafaelrojasmiliani** [AtsushiSakai/PythonRobotics#383]
# Bug description
In the function [rewire](https://github.com/AtsushiSakai/PythonRobotics/blob/master/PathPlanning/RRTStar/rrt_star.py#L152), the `edge_node` node should substitute `near_node` in `self.node_list[i]`. However, the actual procedure does not update the father of the children of `near_node`. 

In fact, in [line 154](https://github.com/AtsushiSakai/PythonRobotics/blob/7442bdceb18b6157b733311ffcc2d544eeab901a/PathPlanning/RRTStar/rrt_star.py#L154) a reference to the node `self.node_list[i]` is stored in `near_node`. After that the function steer returns another object (which is essentially a copy of `near_node`) which is stored in `edge_node`. If there are no collisions, `edge_node` substitutes `near_node` in `self.node_list[i]`. It follows that all the children of `near_node` will have its parent member pointing to `near_node` and not to the node in `self.node_list[i]`. This produce "ghost" nodes in the solution path.

# Expected behaviour
 
It is possible to simple update the values in the instance referenced by `near_node` in [line 154](https://github.com/AtsushiSakai/PythonRobotics/blob/7442bdceb18b6157b733311ffcc2d544eeab901a/PathPlanning/RRTStar/rrt_star.py#L154). The  the nodes will update their parent automatically.

# Note
Please, correct me if I'm wrong. Otherwise if it is possible I can fix this and provide my contribution.

# Desktop
 Ubuntu 18.04, Python3

**Comment by AtsushiSakai** [comment]
Thank you for your report. Could you please create a PR? let’s discuss in the PR.
