### ISSUE TITLE
Data Association

### ISSUE THREAD

**Issue by theColorfulRainbow** [AtsushiSakai/PythonRobotics#398]
Hello,
Kinda new to SLAM, however, I'm trying to get a working version with only distance sensors available.
I was wondering if you guys have fastSLAM with unknown data association,
I noticed that you simulate RFIDs, so once you sense a landmark, you know which one it is, because of a unique id; thus you never do data association.
I was just wondering if that is true as I couldn't find that step anywhere.
Regards.
P.S. You also know the number of landmarks present from the begging of the simulation .... which would mean that you perform fastSLAM with known data-association.

**Comment by AtsushiSakai** [comment]
Thank you for your interest.
I’m sorry I’m busy now and don’t have time to consult your question.
If you need my e-mail consultation, please consider being a sponsor for my oss project 
Using GitHub Sponsor https://github.com/sponsors/AtsushiSakai
	
- One time email consultation (20$)
Using PayPal Donation https://www.paypal.me/myenigmapay/
