### ISSUE TITLE
path tracking

### ISSUE THREAD

**Issue by br1egel** [AtsushiSakai/PythonRobotics#40]
hi, regarding the lqr and mpc steering and speed control for path tracking : do you have any good papers, journals etc. as a reference for that implementation ?
kind regards

**Comment by AtsushiSakai** [comment]
Hi @br1egel . Thank you for your interest to my project. 
These codes are based on this refs:
- Vehicle Dynamics and Control | Rajesh Rajamani | Springer http://www.springer.com/us/book/9781461414322
- Towards fully autonomous driving: Systems and algorithms - IEEE Conference Publication http://ieeexplore.ieee.org/document/5940562/
- ApolloAuto/apollo: An open autonomous driving platform https://github.com/ApolloAuto/apollo
- MPC Course Material - MPC Lab @ UC-Berkeley http://www.mpc.berkeley.edu/mpc-course-material
