### ISSUE TITLE
Help needed in deciding "mapping" and "path-planning" algorithms

### ISSUE THREAD

**Issue by pra-dan** [AtsushiSakai/PythonRobotics#405]
Hello guys, kudos to this amazing work ! :fireworks: 

I have gone through your site and discovered several algorithms for SLAM: mapping as well as path planning. But I am in a dilemma and can't decide how to select the right ones for my application. Please use your expertise to assist me. :handshake: 

## Overview

I am trying to develop a garden-plant watering robot that finds its path along the garden pots and waters them en-route. 
These pots are arranged in several arrays. The robot needs to find the path that traverses all the pots and when it comes across any pot, aligns itself to it and waters it, then moves forward to the next pot/next row.  

## Hardware
The robot is equipped with GPS, Stereocameras and IMU.

## Problem Statement
The keypoints/key problems that I am tacking are:
1. How to start with the map generation ? (Probably, it will be 2D)
2. How to mark these landmarks (pots) in the map ?
3. Which path-planning algorithm can provide an optimal path, suitable for this application ?

Please help me in any ways possible. Any resource will be great ! :child:

**Comment by AtsushiSakai** [comment]
Thank you for your interest.

I’m sorry I’m busy now and don’t have time to consult your question.
If you need my e-mail consultation, please consider being a sponsor for my oss project or donation.
- Once a week email consultation
Using GitHub Sponsor https://github.com/sponsors/AtsushiSakai

- One time email consultation (20$)
Using PayPal Donation https://www.paypal.me/myenigmapay/

Best
