### ISSUE TITLE
Unittests display animation

### ISSUE THREAD

**Issue by raghuramshankar** [AtsushiSakai/PythonRobotics#420]
**Describe the bug**
When running unittests, the script `A_Star_searching_from_two_side.py` runs its tests and displays animation as well, which makes things slow. Some other unit tests print out information on the terminal.

**Expected behavior**
I think we should run tests without showing animation, print something in the terminal only if a unit test fails.

**Screenshots**
![bug_screenshot_20201010](https://user-images.githubusercontent.com/40054659/95650835-8bd9e180-0ae6-11eb-901d-54a082c723ff.png)

**Desktop (please complete the following information):**
 - Python version 3.8.1
 - Numpy version 1.18.3
 - Matplotlib version 3.2.1
 - Scipy version 1.5.1
 - Pandas version 1.0.5

**Comment by AtsushiSakai** [comment]
Hi. Thank you for reporting. Can you create a PR to fix it?

**Comment by raghuramshankar** [comment]
Sure, I can do that.
