### ISSUE TITLE
Cannot understand the algorithms

### ISSUE THREAD

**Issue by tanmayj2020** [AtsushiSakai/PythonRobotics#428]
Hi Atsushi 
I am an undergraduate student and want to learn the maths behind the algorithms which I am not able to understand by seeing your code Which resources should i prefer

**Comment by AtsushiSakai** [comment]
Hi.
Thank you for your interest.

I’m sorry I’m busy now and don’t have time to consult your question.
If you need my email consultation, please consider being a sponsor for my oss project or donation.
- Once a week email consultation (50$ / month)
Using GitHub Sponsor https://github.com/sponsors/AtsushiSakai
- One time email consultation (20$)
Using PayPal Donation https://www.paypal.me/myenigmapay/
 
Best.
