### ISSUE TITLE
pi_2_pi

### ISSUE THREAD

**Issue by supericeandfire** [AtsushiSakai/PythonRobotics#432]
Hi, can I ask you the meaning of pi_2_pi function in fastslam2 ?

**Comment by AtsushiSakai** [comment]
Hi.
Thank you for your question.

I’m sorry I’m busy now and don’t have time to consult your question.
If you need my email consultation, please consider being a sponsor for my oss project or donation.
- Once a week email consultation (50$ / month)
Using GitHub Sponsor https://github.com/sponsors/AtsushiSakai
- One time email consultation (20$)
Using PayPal Donation https://www.paypal.me/myenigmapay/
 
Best.
