### ISSUE TITLE
system path problem in some test source codes

### ISSUE THREAD

**Issue by threepebbles** [AtsushiSakai/PythonRobotics#434]
**Describe the bug**
/tests/test_a_star.py, /tests/test_a_star_searching_two_side.py, /tests/test_a_star_variants.py
~~~python
sys.path.append(os.path.dirname(__file__) + "/../")
~~~
should be updated to 
~~~python
sys.path.append(os.path.dirname(os.path.abspath(__file__)) + "/../")
~~~

**Expected behavior**

**Screenshots**
![Screenshot from 2020-11-06 02-26-12](https://user-images.githubusercontent.com/28076054/98275003-7a95cf00-1fd7-11eb-9eea-7c8abaff6f8d.png)

**Desktop (please complete the following information):**
 - Python version (This repo only supports Python 3.7.x or higher).
 - Each library version

![Screenshot from 2020-11-06 02-27-01](https://user-images.githubusercontent.com/28076054/98275085-95684380-1fd7-11eb-9bdd-183257d34dc9.png)

**Comment by AtsushiSakai** [comment]
In my environment, `os.path.dirname(__file__)` is equivalent to  `os.path.abspath(__file__)`. The `__file__` is not absolute path in your enviroment?
