### ISSUE TITLE
Question about the lqr state space model 

### ISSUE THREAD

**Issue by jadhm** [AtsushiSakai/PythonRobotics#437]
Hi, 

For the lqr steer control are you using a kinematic model of the bicycle model or the dynamic model ? and do you have any reference of how  the state space model  is derived (A and B matrices) ? 

Edit:
I tried to derive the state space model using this reference 
https://www.researchgate.net/publication/323722783_A_Tutorial_On_Autonomous_Vehicle_Steering_Controller_Design_Simulation_and_Implementation

 But the final kinematic model is this. I got the same B matrix but I see some differences in the A matrix could you please give me some more information of how your model is derived ?

![image](https://user-images.githubusercontent.com/25588361/98649759-3fc5cb00-2338-11eb-9cd1-475c13fe6eca.png)

Thanks in advance.

**Comment by AtsushiSakai** [comment]
Hi.
Thank you for your question.

I’m sorry I’m busy now and don’t have time to consult your question.
If you need my email consultation, please consider being a sponsor for my oss project or donation.
- Once a week email consultation (50$ / month)
Using GitHub Sponsor https://github.com/sponsors/AtsushiSakai
- One time email consultation (20$)
Using PayPal Donation https://www.paypal.me/myenigmapay/
 
Best.
