### ISSUE TITLE
Can we also use the pygame library?

### ISSUE THREAD

**Issue by sarimmehdi** [AtsushiSakai/PythonRobotics#440]
Hello. While I understand wanting to do everything using only matplotlib and numpy, I think also including pygame can make generating certain scenarios very easy. There are many situations where you would like to have moving obstacles (for example) and simulating that using matplotlib can be cumbersome. Having pygame deal with stuff like this will allow us to program path planning, mapping, and other kinds of robotic algorithms more easily.

**Comment by AtsushiSakai** [comment]
Thank you for your request. That is difficult decision because I'm not familiar with pygame. Can you create a sample PR to show how pygame is useful?
