### ISSUE TITLE
Can't run pure_pursuit.py in close loop rrt*

### ISSUE THREAD

**Issue by LeoYang94** [AtsushiSakai/PythonRobotics#442]
Hello,when I want to run pure_pursuit.py in close loop rrt*,I find the "rrt_course.csv" file is empty,so I can't run this python file.Can you sent me this file? Thanks!

**Comment by AtsushiSakai** [comment]
I'm sorry I don't have it because it was for debug use. I think I should remove the `main2` function in the file.
