### ISSUE TITLE
Questions about[PathTracking/stanley_controller.py]

### ISSUE THREAD

**Issue by longfei1995** [AtsushiSakai/PythonRobotics#448]
**Describe the bug**
The question of solving "error_front_axle"
**Expected behavior**
I see you are using this method(# Project RMS error onto front axle vector) to solve "error_front_axle".
Can you tell me the principle of this method？
It was wrong of me to use this method "error_front_axle = np.hypot(dx[target_idx], dy[target_idx])"

**Screenshots**
![捕获](https://user-images.githubusercontent.com/62555482/102969252-557e0100-4530-11eb-8e9a-17da98e683c2.PNG)

**Comment by AtsushiSakai** [comment]
Thank you for your question.
I’m sorry I’m busy now and don’t have time to consult your question.
If you need my consultation, please consider being a sponsor for my oss project or donation.

Using GitHub Sponsor https://github.com/sponsors/AtsushiSakai

One time email consultation (20$)
Using PayPal Donation https://www.paypal.me/myenigmapay/
