### ISSUE TITLE
Sum of accelerations are being used in cost function instead of sum of square of jerk

### ISSUE THREAD

**Issue by lharikrishnan1993** [AtsushiSakai/PythonRobotics#45]
https://github.com/AtsushiSakai/PythonRobotics/blob/bc296aada55cbe21fd2481f64c916e49fe7d9bef/PathPlanning/FrenetOptimalTrajectory/frenet_optimal_trajectory.py#L177

**Comment by AtsushiSakai** [comment]
@lharikrishnan1993 Hi. Thank you for your bug report. You are right. I misunderstood the cost function.
I fixed it to correct cost function.
Can you check the latest code?

**Comment by lharikrishnan1993** [comment]
That looks right. But getting the derivative from the polynomial solvers might result in better accuracy.
But, jerk typically is a really small value an should not affect the performance of the system.
Thanks for the effort.
Closing.
