### ISSUE TITLE
Question About Path Planning/Optimal Frenet Trajectory Generator 

### ISSUE THREAD

**Issue by BjarneStroustrup-97** [AtsushiSakai/PythonRobotics#463]
Hello I am Pavan I am doing my Masters at University of Michigan. I am trying to generate different Trajectory for a car in 3 lane Highway and eventually My aim is to make the car follow a trajectory avoiding obstacle. 
Initially I am trying to convert by x , y and theta global points  into frenet frame of s and d then develop a different trajectory set in the format of (s, s_d ,s_dd ,l ,l_d ,l_dd). But as i know my car position in global coordinate ...can you kindly tell me how can I convert it into frenet frame ?
I went through the code but I was not able to understand the transformation and I also referred to the paper that used as a reference in this code but I was not able to understand can you kindly tell me how to understand this global to frenet transformation and vice - versa ?
If you have any reference material can you kindly let me know ?

Thank You

**Comment by AtsushiSakai** [comment]
Thank you for your question.
I’m sorry I’m busy now and don’t have time to consult your question.
If you need my consultation, please consider being a sponsor for my oss project or donation.

Using GitHub Sponsor https://github.com/sponsors/AtsushiSakai

One time email consultation (20$)
Using PayPal Donation https://www.paypal.me/myenigmapay/
