### ISSUE TITLE
Dubins path lenght is incorrect if curvature is changed

### ISSUE THREAD

**Issue by AlexandreBorowczyk** [AtsushiSakai/PythonRobotics#471]
![image](https://user-images.githubusercontent.com/1645032/106210594-15e0af80-6195-11eb-9d22-fdf84092e0d8.png)
Curvature 1.0
Distance 22.18 (Ok seems right)

![image](https://user-images.githubusercontent.com/1645032/106210646-3446ab00-6195-11eb-82aa-bb9f2b93841f.png)
Curvature 2.0
Distance 43.52 (Makes no sense)

![image](https://user-images.githubusercontent.com/1645032/106210699-4e808900-6195-11eb-89dd-c3802c776050.png)
Curvature 0.1
Distance: 8.42 (Impossible) 

 - Python version 3.7.8

**Comment by lhoupert** [comment]
any idea why @AtsushiSakai ?

**Comment by AtsushiSakai** [comment]
Hi. Thanks for reporting. I fixed the bug. Please check the latest code.
