### ISSUE TITLE
unable to run n_joint_arm_to_point_control

### ISSUE THREAD

**Issue by mikelty** [AtsushiSakai/PythonRobotics#486]
i'm using windows 10, python 3.9 and everything and the following instruction:
python n_joint_arm_to_point_control.py
error:ModuleNotFoundError: No module named 'ArmNavigation'
i was able to get many other simulations to run though.

**Comment by AtsushiSakai** [comment]
Hi. Thank you for reporting. Yes. we started to use module for some scripts.
Maybe you run the script from the script directory. You need to add a root dir path like
```
import sys, os
sys.path.append(os.path.join(os.path.dirname(__file__), '..', '..'))
```
