### ISSUE TITLE
[Feature Request] jerk limit on quintic polynomial planner

### ISSUE THREAD

**Issue by jwdinius** [AtsushiSakai/PythonRobotics#49]
The quintic polynomial planner has only limits on acceleration, not on jerk.  I have added the limiting and am ready to submit a pull request.  Is this a feature that you would like added?

**Comment by AtsushiSakai** [comment]
Hi. @jwdinius . Thank you so much for your interest about the repo.
Oh, that's interesting. Can you submit the PR?
I want to check it.

**Comment by jwdinius** [comment]
Cool!  I have submitted the pull request.

**Comment by AtsushiSakai** [comment]
I merged it. Thank you for your contribution again!.

**Comment by jwdinius** [comment]
Thanks @AtsushiSakai!  Great work on this repo!  I look forward to using it in the future!
