### ISSUE TITLE
Voronoi Roadmap

### ISSUE THREAD

**Issue by FCostaS** [AtsushiSakai/PythonRobotics#514]
**Expected behavior**
Could someone explain to me why this occurs?

**Screenshots**
![github_Voronoi](https://user-images.githubusercontent.com/20869087/121105672-eb55d180-c7da-11eb-8872-885f9e5bf5e0.png)

**Comment by AtsushiSakai** [comment]
Thank you for reporting it. That might be a bug. Could you give us the code reproducing the big?

**Comment by FCostaS** [comment]
> Thank you for reporting it. That might be a bug. Could you give us the code reproducing the big?
It's here.
[main.zip](https://github.com/AtsushiSakai/PythonRobotics/files/6627306/main.zip)

**Comment by mbosetti** [comment]
I ran in to the same issue with the road mapper. It turned out to be a simple hypot check. I assume it will work for this as well

https://github.com/AtsushiSakai/PythonRobotics/pull/522
