### ISSUE TITLE
Erroneous backward motion in reeds-sheep path

### ISSUE THREAD

**Issue by lhoupert** [AtsushiSakai/PythonRobotics#518]
**Describe the bug**
in some case the reeds-sheep interpolation provide erroneous data point at the beginning of the path

**Expected behavior**
No backward motion

**Screenshots**
![image](https://user-images.githubusercontent.com/10154151/123280305-f877fd80-d508-11eb-9cd7-b10584634429.png)

Code top reproduce the bug:

```python
start_x=-90.0356
start_y=-136.6776
start_yaw=-1.7133897266828333
end_x=-90.4311
end_y=-136.6672
end_yaw=1.670105561233374
curvature=5.0
step_size=0.05

px, py, pyaw, mode, clen = reeds_shepp_path_planning(
        start_x,
        start_y,
        start_yaw,
        end_x,
        end_y,
        end_yaw,
        curvature,
        step_size,
    )

fig, ax = plt.subplots()
plt.cla()
plt.plot(px, py,'+-', label="final course " + str(mode))

# plotting
plot_arrow(start_x, start_y, start_yaw)
plot_arrow(end_x, end_y, end_yaw)
```

**Desktop (please complete the following information):**
 - Python version 3.9

**Comment by AtsushiSakai** [comment]
@lhoupert Thank you for reporting. I think the issue was fixed in #529. Please check the latest code.
