### ISSUE TITLE
Hybrid A* planner simulation should be added

### ISSUE THREAD

**Issue by AtsushiSakai** [AtsushiSakai/PythonRobotics#54]

**Comment by jwdinius** [comment]
I'll have a crack at this in the next couple of weeks.  I have implemented in the past so it shouldn't be too difficult.  Do you still want this @AtsushiSakai?

**Comment by AtsushiSakai** [comment]
@jwdinius Hi. Thank you for your suggestion. Yes. I still want it!!. Your PR is welcome.

**Comment by xinbada007** [comment]
Hey What's the progress now? Anyone adding the Hybrid-A* simulation? 

Just wondering if it just misses the simulation implementation but the algorithm is complete?

**Comment by AtsushiSakai** [comment]
@xinbada007 I'm waiting a someone's PR.

**Comment by jwdinius** [comment]
I have been unable to complete this work yet.  I will try to have a PR by Christmas @xinbada007 @AtsushiSakai

**Comment by AtsushiSakai** [comment]
@jwdinius Thank you. Take your time : ) .

**Comment by renegadephysicist** [comment]
There is an implementation [here in Julia ](https://github.com/XiaojingGeorgeZhang/OBCA/blob/master/AutonomousParking/hybrid_a_star.jl) that might be useful.

**Comment by jwdinius** [comment]
I haven't forgotten about this.  I missed the Christmas timeline, but I will be working on it this weekend @AtsushiSakai @xinbada007

**Comment by AtsushiSakai** [comment]
@jwdinius Thank you for your comment. Take your time and enjoy the end of the year.

**Comment by AtsushiSakai** [comment]
@jwdinius Hi. Are you working this issue?

**Comment by jwdinius** [comment]
I'm sorry @AtsushiSakai, I've been unable to find the time to finish this.  If anyone has the time before I can finish, here's a repo I am translating to python https://github.com/informramiz/Hybrid-Astar-search-algorithm.git.  I will continue working on it, but I have no estimated time of completion.

**Comment by zhengzh** [comment]
BFS algorithm in Informaramiz's repo is wrong actually.

**Comment by jwdinius** [comment]
@zhengzh thanks for the response.  The implementation generates reasonable looking paths.  What specifically is wrong about the implementation?  If you know of something else to use as a starting point, I would be interested to hear about it.

**Comment by zhengzh** [comment]
@jwdinius , Hi. As we know, in BFS algorithm, we should put every children of a parent node into the queue, but he only puts the minimum cost node into the queue (in [line](https://github.com/informramiz/Hybrid-Astar-search-algorithm/blob/419e181e7eec982d25f710d0610d2214e7d0047e/HybridAstarAlgorithm/src/hybrid_breadth_first.cpp#L558)), but forgets to put other nodes into the queue. I test the program with the `MAZE` (not the `EMPTY_MAZE`) and it gives 60 steps to reach the goal, but in this [repo](https://github.com/ChenBohan/Robotics-Path-Planning-03-Hybrid-A-Star), it uses A* algorithm (not hybrid A*) and only needs 38 steps to reach the goal, and we know both algorithms should give the same optimal path. I don't know why the file is named as `hybrid_breadth_first.cpp`, I think BFS won't help save expanded nodes. The best and simplest hybrid A* implementation I have found is in this repo https://github.com/AtsushiSakai/HybridAStarTrailer, which is the just the same as the original [paper](https://ai.stanford.edu/~ddolgov/papers/dolgov_gpp_stair08.pdf) described, although I never learn julia language before, I can still understand the code :smile_cat:.

**Comment by jwdinius** [comment]
Ok @zhengzh , your points are well-taken.  I have looked at the implementation and I will work to translate it to python 3.6.  Do we want a more general hybrid a* implementation (like the A* implementation)?  I will do the translation so that the core search algorithm can be easily imported into possible future hybrid a* implementations.

**Comment by zhengzh** [comment]
Nice! @jwdinius, Thank you, please make the `MAZE` a little bit harder like driving a car into a parking space.
![image](https://user-images.githubusercontent.com/3636536/54247946-d6dfeb80-4575-11e9-8748-997f37290c1f.png)

**Comment by jwdinius** [comment]
https://github.com/AtsushiSakai/PythonRobotics/pull/180 addresses this, so I'm stopping work

**Comment by AtsushiSakai** [comment]
@jwdinius @zhengzh I merged #180 . Thank you so much for your help!!
