### ISSUE TITLE
MPC Tracking [xbar] come from

### ISSUE THREAD

**Issue by berlala** [AtsushiSakai/PythonRobotics#544]
In MPC tracking, the operation points [xbar] come from the predict_motion() with the current state[x0] and the control commands[oa, od] from the last cycle.
Why don't use [ox, oy, oyaw, ov] from the MPC result directly?

**Comment by AtsushiSakai** [comment]
Hi.
Thank you for your question.

I’m sorry I’m busy now and don’t have time to consult your question.
If you need my email consultation, please consider being a GitHub sponsor for my OSS project.
