### ISSUE TITLE
EKF SLAM with loop closure

### ISSUE THREAD

**Issue by Ganeshgng** [AtsushiSakai/PythonRobotics#545]
Is it possible to implement EKF SLAM with Loop Closure??
https://github.com/AtsushiSakai/PythonRobotics/tree/master/SLAM/EKFSLAM

**Comment by AtsushiSakai** [comment]
Hi.
Thank you for your question.

I’m sorry I’m busy now and don’t have time to consult your question.
If you need my email consultation, please consider being a GitHub sponsor for my OSS project.
