### ISSUE TITLE
EKFSLAM ipynb issue

### ISSUE THREAD

**Issue by Ganeshgng** [AtsushiSakai/PythonRobotics#546]
https://github.com/AtsushiSakai/PythonRobotics/blob/master/SLAM/EKFSLAM/ekf_slam.ipynb

Got a warning
usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:27: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray

Expected but not happened: Can not see the animation output in the python notebook

**Comment by AtsushiSakai** [comment]
Thank you for reporting. Can you create a PR for it?

**Comment by kajal-puri** [comment]
Hi, if this issue isn't solved. Can you assign this to me?

**Comment by AtsushiSakai** [comment]
Close by #552
