### ISSUE TITLE
moving object detection and tracking should be added.

### ISSUE THREAD

**Issue by AtsushiSakai** [AtsushiSakai/PythonRobotics#57]

**Comment by matthewgan** [comment]
which algorithm of moving object detection and tracking u want to add?
using cameara and opencv?

**Comment by AtsushiSakai** [comment]
@matthegan Hi. I have no idea now.. I’m surveying some papers to know which approach is comonly used. But maybe I will use a 2D point cloud based approach because it is easy to implement.
