### ISSUE TITLE
Arm Obstacle avoidance

### ISSUE THREAD

**Issue by arielc-brillianetor** [AtsushiSakai/PythonRobotics#591]
Hey,
I was wondering if in the RRT calculations for the arm navigation for N-link and collision avoidance you take into account that the robot between the links may collide with an obstacle. Looking at the code I noticed that you check the distance between each joint and the obstacles but I didn't find code which checks the distance between the links themselves which connect the joints and the obstacles.
If I'm missing something please let me know, it would be a big help. If not, do you know of a smart way of doing so?
Thanks for all of the great work you're doing!!

**Comment by AtsushiSakai** [comment]
’m sorry I’m busy now and don’t have time to consult your question.
If you need my email consultation, please consider being a sponsor for my oss project or donation.
- Once a week email consultation (50$ / month)
Using GitHub Sponsor https://github.com/sponsors/AtsushiSakai
- One time email consultation (20$)
Using PayPal Donation https://www.paypal.me/myenigmapay/
