### ISSUE TITLE
Kp_beta gain with a negative value!

### ISSUE THREAD

**Issue by Muhammad-Yazdian** [AtsushiSakai/PythonRobotics#600]
**Describe the bug**
- The controller only works when the Kp_beta gain is set to a negative value. 

https://github.com/AtsushiSakai/PythonRobotics/blob/54be632f716f9913a89a166b7d8a722e156da7d0/Control/move_to_pose/move_to_pose.py#L19

**Expected behavior**
- Gains are usually positive values and if the Kp_beta is set to a positive value, the robot will rotate forever at the target location! 

**Possible Solution**
- There might be a simple sign flip error in the control law calculations. 

**Desktop info:**
 - Python version 3.7
 - Windows

**Comment by qlibp** [comment]
Not sure why we need to set Kp_beta > 0? From the book, Kp_beta should < 0
