### ISSUE TITLE
Error in curvature formula in Cubic Spline

### ISSUE THREAD

**Issue by araffin** [AtsushiSakai/PythonRobotics#64]
Hello,

I think there is a power of 3/2 missing in the curvature formula for the cubic spline:
https://github.com/AtsushiSakai/PythonRobotics/blob/master/PathPlanning/CubicSpline/cubic_spline_planner.py#L167

Instead of:
```python
k = (ddy * dx - ddx * dy) / (dx ** 2 + dy ** 2)
```
it should be
```python
k = (ddy * dx - ddx * dy) /((dx ** 2 + dy ** 2)**(3/2))
```
no ?

**Comment by AtsushiSakai** [comment]
@araffin Hi. Thank you for your interest about my repo.
Yes, you are right. My reference approximates the power part.
But, your formula is better than it. I fixed it.
Thank you!!
