### ISSUE TITLE
HybridAStar: Calculation of Bubble radius

### ISSUE THREAD

**Issue by trickster-117** [AtsushiSakai/PythonRobotics#644]
**Describe the bug**
The radius of the bubble containing a rectangular vehicle is:
 r = sqrt( (L/2)² + (W/2)²)
In the code it is:
r = sqrt( (L/2)² + 1)
See: https://github.com/AtsushiSakai/PythonRobotics/blob/e494ed6eaecb00fdf13fb361db947498c70d898c/PathPlanning/HybridAStar/car.py#L22
This is valid given the default width of W=2. but not if the width is changed to another value.

**Expected behavior**
The formula should be changed as shown.

**Comment by AtsushiSakai** [comment]
@trickster-117 Thank you for reporting. PR is welcome.

**Comment by vidit21srivastava** [comment]
Is this issue still open for working upon?
I would like to work on this issue.

**Comment by trickster-117** [comment]
Yes, this issue is still open, I haven't fixed it yet, but I will do it today. Further I found some improvements that would be nice to implement. I will try to implement them today.
