### ISSUE TITLE
PathPlanning algorithms(A* and Dijkstra) not showing final paths 

### ISSUE THREAD

**Issue by kartikmadhira1** [AtsushiSakai/PythonRobotics#67]
**System Information -**
Python version - 3.6.5
Matplotlib version - 2.2.2
System OS - MacOS High Sierra 

**Description**
Running the Dijkstra python file, runs the grid search perfectly, but as soon as the goal is reached, the plot hangs and is unable to plot the final path. 
I modified it for my system by plotting the path in the final path calculation function itself.
Is this a library issue? If yes, then please clarify.

**Comment by AtsushiSakai** [comment]
@kartikmadhira1 Did the original code work correctly before you modified it? and does other script work?

**Comment by kartikmadhira1** [comment]
The original code was working but only till the goal was reached and then the final path isn't traced. I just plotted the final path (final path calculation function ) itself so now it traces the path.

See this picture for reference(error):
<img width="1310" alt="screen shot 2018-06-13 at 7 55 40 am" src="https://user-images.githubusercontent.com/16814100/41413842-f1da8aac-7001-11e8-982f-f776812fc8c9.png">

**Comment by AtsushiSakai** [comment]
@kartikmadhira1 I'm sorry, I don't know what is happening. Maybe that is a problem from matplotlib or other library. I cannot help you. sorry.
