### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by adityaanirudhk** [AtsushiSakai/PythonRobotics#682]
Hi. Since this is a platform which deals with the localization and mobility of robots, I have few ideas related to military robotics. Using your concepts of probabilistic robotics, trajectory planning and mobility of robots, could you tell me wether I could host my ideas in this platform and work together on the projects if they seem worthy of having a shot?

A response is awaited

**Comment by AtsushiSakai** [comment]
Thank you for your interest. 
I cannot say anything because I don't know your idea. So, please create an issue about one of your idea.

**Comment by adityaanirudhk** [comment]
Done!
