### ISSUE TITLE
Documentation for lqr_speed_steer_control.py

### ISSUE THREAD

**Issue by mrunaljsarvaiya** [AtsushiSakai/PythonRobotics#705]
Is there any documentation on what the variables being passed around in lqr_steer_control.py mean and a reference to the formulas used?

I'm a little confused as to how the desired path point is selected using `calc_nearest_index`. Why does the index get incremented if you're selecting the current goal to be the path point closest to you? In theory wouldn't you simply hone in on the first index you're trying to reach and never move away from it since lqr would move you towards that index? Or cause you're also selecting a goal velocity do you naturally overshoot that position and start moving towards the next one?

**Comment by Zireael07** [comment]
Why close? I can't see any commits that would've improved the docs...

**Comment by AtsushiSakai** [comment]
I agree we can improve the doc, so reopen this.

**Comment by mrunaljsarvaiya** [comment]
I closed it cause I was able to figure out what I didn't understand, but yeah it could use more formal documentatino

**Comment by AtsushiSakai** [comment]
Your PR is welcome to add your findings!!

**Comment by Kim8178184977** [comment]
Can I work on the doc? , because I am a beginner and not too good at the code work

**Comment by AtsushiSakai** [comment]
Yes!! Anyone’s PR is welcome!!

**Comment by Kim8178184977** [comment]
thanks, sir can I see the details and the code directory

**Comment by Kim8178184977** [comment]
Sir, is the Project based on Reinforcement learning?
