### ISSUE TITLE
No module named 'utils.angle'

### ISSUE THREAD

**Issue by baqwas** [AtsushiSakai/PythonRobotics#709]
**Describe the bug**
`
Input In [9], in <cell line: 17>()
     14 import matplotlib.pyplot as plt
     15 import numpy as np
---> 17 from utils.angle import rot_mat_2d

ModuleNotFoundError: No module named 'utils.angle'
`

**Expected behavior**
No ModuleNotFoundError message because **utils** was installed from pypi:
`$ python3 -m pip install utils`

**Screenshots**
see _Describe the bug_ section above

**Desktop (please complete the following information):**
 - Python version 3.10
 - Each library version
 - OS version Ubuntu 22.04

**Comment by Abhishekee** [comment]
I am having same issue
How have you solved?
