### ISSUE TITLE
several questions in frenet_optimal_trajectory.py?

### ISSUE THREAD

**Issue by kecaiwu** [AtsushiSakai/PythonRobotics#71]
The class name "quinic_polynomial" means "quintic_polynomial"? And, why use the **quintic polynomial** in lateral motion planning and **quartic polynomial** in longitudinal motion planning? Thank you!

**Comment by AtsushiSakai** [comment]
@kecaiwu Hi. Yes, that is typo. Thank you.
That came from the number of constraints for control. Please see the paper.
