### ISSUE TITLE
Using ``*`` for matrix multiplication has been deprecated since CVXPY 1.1

### ISSUE THREAD

**Issue by baqwas** [AtsushiSakai/PythonRobotics#710]
Not a bug! Simply a note that I will work on suppressing the warnings. Thanks.

**Describe the deprecated feature**
  warnings.warn(msg, UserWarning)
/usr/local/lib/python3.10/dist-packages/cvxpy/expressions/expression.py:593: UserWarning: 
This use of ``*`` has resulted in matrix multiplication.
Using ``*`` for matrix multiplication has been deprecated since CVXPY 1.1.
    Use ``*`` for matrix-scalar and vector-scalar multiplication.
    Use ``@`` for matrix-matrix and matrix-vector multiplication.
    Use ``multiply`` for elementwise multiplication.
This code path has been hit 2590 times so far.

  warnings.warn(msg, UserWarning)

**Expected behavior**
No warnings.

**Screenshots**
Working on making changes to the code to suppress the warnings; I will submit a PR if successful in due course. Thanks.

**Desktop (please complete the following information):**
 - Python version 3.10
 - Each library version
 - OS version Ubunut 22.04

**Comment by AtsushiSakai** [comment]
Thank you for reporting. PR is welcome!!
