### ISSUE TITLE
ModuleNotFoundError: No module named 'utils.angle'

### ISSUE THREAD

**Issue by ddwy** [AtsushiSakai/PythonRobotics#750]
ModuleNotFoundError: No module named 'utils.angle'

**Comment by AtsushiSakai** [comment]
Thank you for reporting. Which script did you run?

**Comment by AlessioGrespi** [comment]
I have the same issue, I am trying to run the Dubins path script

**Comment by shu-qing** [comment]
same issue. 
sys.path.append(str(pathlib.Path(__file__).parent.parent.parent))  appends the wrong directory
str(pathlib.Path(__file__).parent.parent.parent   returns   "."

**Comment by AtsushiSakai** [comment]
I cannot reproduce this issue. I'm not sure why `str(pathlib.Path(file).parent.parent.parent` returns ".". This should return PythonRobotics top directory path. More detailed information is needed.
