### ISSUE TITLE
Documentation using Jupyter notebook

### ISSUE THREAD

**Issue by AtsushiSakai** [AtsushiSakai/PythonRobotics#77]
.ipynb file may be good for documentation of each algorithm.

**Comment by node-py** [comment]
I can help with jupyter notebook for each algorithm.

**Comment by kartikmadhira1** [comment]
I have too implemented similar codes taking help from some of the codes in the Repo so I can help too. Can you be more specific regarding the documentation? As in to add in-depth text (math, diagrams, etc.) to each block of code or just superficially explain as to what each block of code does?

**Comment by AtsushiSakai** [comment]
@kartikmadhira1 Thank you for your comment. Yes, it is great to include it's math, algorithm, and diagram. I think code description is not needed because there are comments on the code. If you read the doc and code, you can understand the basic idea of the algorithm. This is the goal of this project.

**Comment by kartikmadhira1** [comment]
@AtsushiSakai Sure then. I'll try to get a first draft version on Astar and Dijkstra and present it to you. Will try to get it done by end of next week.

**Comment by AtsushiSakai** [comment]
@kartikmadhira1 Oh. great. I appreciate your help!!.

**Comment by AtsushiSakai** [comment]
I'm trying to write a jupyter notebook for MPC.
[PythonRobotics/notebook\.ipynb at master · AtsushiSakai/PythonRobotics](https://github.com/AtsushiSakai/PythonRobotics/blob/master/PathTracking/model_predictive_speed_and_steer_control/notebook.ipynb)

- [ ] finish jupyter notebook for MPC

**Comment by kartikmadhira1** [comment]
@AtsushiSakai I am working on writing documentation regarding [Kalman Filters](https://github.com/kartikmadhira1/Robotics-Algorithms/blob/master/Filters/KF_notes.ipynb)- concepts and math with examples from a few sources. We can add it to the EKF section if you want.

**Comment by AtsushiSakai** [comment]
@kartikmadhira1 Nice. Could you make PR?

**Comment by AtsushiSakai** [comment]
MPC's notebook is done. Next one is EKF.

- [ ] [PythonRobotics/notebook\.ipynb at master · AtsushiSakai/PythonRobotics](https://github.com/AtsushiSakai/PythonRobotics/blob/master/Localization/extended_kalman_filter/notebook.ipynb)

**Comment by nithin1995** [comment]
Hi, I am interested to contribute. I am new to this field, and interested to learn and contribute. I would like you suggest an algorithm for me to start working on the documentation.

**Comment by AtsushiSakai** [comment]
@nithin1995 Thank you. How about EKF? [PythonRobotics/notebook\.ipynb at master · AtsushiSakai/PythonRobotics](https://github.com/AtsushiSakai/PythonRobotics/blob/master/Localization/extended_kalman_filter/notebook.ipynb)

**Comment by sunnytokyo** [comment]
hi atushi, I wud also like to contribute for codes and docs. Do contributors get to feature as authors for the project?

**Comment by daniel-s-ingram** [comment]
I'll start working on Jupyter notebooks for the algorithms I've submitted!

**Comment by AtsushiSakai** [comment]
@daniel-s-ingram That's great!! Your PR is welcome.

**Comment by AtsushiSakai** [comment]
#130

**Comment by adelizer** [comment]
hi @AtsushiSakai, I would like to help with creating a documentation notebook for fastSLAM1.0 if it is not in progress yet.

**Comment by amirx96** [comment]
@AtsushiSakai Is there any documentation for the LQR steer controller? The closest source I could find was https://arxiv.org/pdf/1803.03758.pdf on page 10.

I am not sure how you incorporate dt into the A matrix.

**Comment by AtsushiSakai** [comment]
I'm closing this issue once for v1.0 release.
