### ISSUE TITLE
MPC module documentation

### ISSUE THREAD

**Issue by erlete** [AtsushiSakai/PythonRobotics#777]
I'm opening this issue in order to gather information about the evident lack of documentation on the [Path Tracking MPC module](https://github.com/AtsushiSakai/PythonRobotics/blob/master/PathTracking/model_predictive_speed_and_steer_control/model_predictive_speed_and_steer_control.py).

My intention is to open a PR including all relevant documentation on the methods of the module mentioned below, but I can only get so far without information about the scientific basis of the code. As of now, the only referenced documentation sources are the [notebook](https://github.com/AtsushiSakai/PythonRobotics/blob/master/PathTracking/model_predictive_speed_and_steer_control/Model_predictive_speed_and_steering_control.ipynb) (which returns a 404) and the [Real-time Model Predictive Control (MPC), ACADO, Python | Work-is-Playing](http://grauonline.de/wordpress/?page_id=3244). However, this is not sufficient for extensive documentation of each method, so any comments on the matter are highly appreciated!

_Note: I usually document code using the [Google Docstring Format](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html), but I'm open to suggestions on different formats._

**Comment by AtsushiSakai** [comment]
This document is not enough? https://atsushisakai.github.io/PythonRobotics/modules/path_tracking/model_predictive_speed_and_steering_control/model_predictive_speed_and_steering_control.html
But, any kind of document improvement is welcome.
