### ISSUE TITLE
Point cloud sampling axes3d error

### ISSUE THREAD

**Issue by lenhatquang2512** [AtsushiSakai/PythonRobotics#783]
Hi Professor,

I tried to run "point_cloud_sampling.py" in the Mapping folder, and I met this error:

Axes3D currently only supports the aspect argument 'auto'. You passed in 'equal'.

So I just changed plt.axis("equal") in line 127 to plt. axis("auto") and it worked again.

**Comment by AtsushiSakai** [comment]
Which matplolib version are you using?

**Comment by lenhatquang2512** [comment]
I used matplotlib 3.5.1. I just checked the requirement file, which states that we need matplotlib 3.6.3 to run. Sorry about the confusion.
