### ISSUE TITLE
Grid based sweep coverage algorithm not sweeping the whole 2D grid

### ISSUE THREAD

**Issue by nino192** [AtsushiSakai/PythonRobotics#827]
Tested this algorithm in some cases of irregularly shaped polygons and the algorithm does not cover the whole 2d grid.
Example images, integrated the algorithm with ros2 and visualised with rviz:

![Screenshot from 2023-05-10 13-20-40](https://github.com/AtsushiSakai/PythonRobotics/assets/113939473/4e8cffdd-af54-4173-a049-6ba243460193)

![Screenshot from 2023-05-10 13-24-39](https://github.com/AtsushiSakai/PythonRobotics/assets/113939473/0d8490f0-ead9-49d8-8e7a-9428d527d235)

![Screenshot from 2023-05-10 13-25-41](https://github.com/AtsushiSakai/PythonRobotics/assets/113939473/71f71c4f-d296-4a1f-a714-836b8f4ca3eb)

It appears to me that there is a bug related to direction in which sweep path begins...

Using:
 - Python version 3.10.6.
 - Ubuntu 22.04.2 LTS

**Comment by AtsushiSakai** [comment]
I think it is a limitation of the current algorithm. It only supports convex areas, not a bug. I think you should use another algorithm.
