### ISSUE TITLE
Performance increase 

### ISSUE THREAD

**Issue by AlexisTM** [AtsushiSakai/PythonRobotics#83]
https://github.com/AtsushiSakai/PythonRobotics/blob/8652a4b7d1cc12682829b8929b528ef9b7cefb0f/PathTracking/lqr_steer_control/lqr_steer_control.py#L139-L156

In the following function, the line 143 is more expensive than it could be:
* `abs` is not required: result of SQRT and result of sum of squared values is always positive
* `sqrt` is expensive, while the logic is the same without using it

Therefore, I would do the following optimization (replacing 143 to 147):

```python
     d = [idx ** 2 + idy ** 2 for (idx, idy) in zip(dx, dy)] 

     mind = min(d) 

     ind = d.index(mind) 

     mind = math.sqrt(mind)
```

**Comment by AtsushiSakai** [comment]
@AlexisTM  Good idea. Can you create a PR?
