### ISSUE TITLE
Add Docker Image for easier setup

### ISSUE THREAD

**Issue by Faizan-Alam-1** [AtsushiSakai/PythonRobotics#830]
I would like to propose adding a Docker image to the project. 

It will be easier for contributors and users to set up and run the project since they won't have to manually install dependencies.

I would be glad to work on this and create a pull request if the maintainers agree.
@AtsushiSakai

**Comment by AtsushiSakai** [comment]
Thank you for your proposal. Let me confirm one thing. How are you providing matplotlib front-end in the docker container?
I think just providing an environment to just run script is easy with docker, but providing matplotlib based animation mechanism needs some considerations.
