### ISSUE TITLE
Project Collaborations

### ISSUE THREAD

**Issue by karanchawla** [AtsushiSakai/PythonRobotics#9]
Hello,

I'm working on dynamic astar planning and other planning algorithms. Would you be interested in accepting pull requests and possibly collaborating on future project development?

**Comment by AtsushiSakai** [comment]
Hi Karan.
Thank you for your interest to my project.
I accept PR about minor bug and issues and questions. 
However, I don't accept PR about new sample code or big PR. 
Because this is my hobby project and for study. 
I'm sorry.

**Comment by karanchawla** [comment]
Sure. That's fine 👍
