### ISSUE TITLE
There's an error in the transformation_matrix of Quadrotor

### ISSUE THREAD

**Issue by KimKreiss** [AtsushiSakai/PythonRobotics#903]
In the code `/AerialNavigation/drone_3d_trajectory_following/Quadrotor.py`
The rotation part of the transformation matrix has an error
https://github.com/AtsushiSakai/PythonRobotics/blob/3fce78a41e56b3bdb183e581bede2b19ea96a5df/AerialNavigation/drone_3d_trajectory_following/Quadrotor.py#L59
The original term `cos(pitch) * cos(yaw)` should be `cos(pitch) * cos(roll)`

This can be verified by calculating the `np.dot(T[:,:3], T[:,:3].T)`, which should equal an identity matrix.

**Comment by UjjwalPardeshi** [comment]
can you assign me this please .

**Comment by AtsushiSakai** [comment]
Can someone paste a link or image for the reference of the quadrotor transformation matrix mathematics here?

**Comment by KimKreiss** [comment]
> Can someone paste a link or image for the reference of the quadrotor transformation matrix mathematics here?

here's a slide https://msl.cs.uiuc.edu/planning/node102.html
