### ISSUE TITLE
grid_based_sweep_coverage_path_planner.py last example the region coverage problem

### ISSUE THREAD

**Issue by kk-1** [AtsushiSakai/PythonRobotics#907]
**Describe the bug**
The last region example in the code:
PathPlanning/GridBasedSweepCPP/grid_based_sweep_coverage_path_planner.py

I mean the last example:
    ox = [0.0, 20.0, 50.0, 200.0, 130.0, 40.0, 0.0]
    oy = [0.0, -80.0, 0.0, 30.0, 60.0, 80.0, 0.0]
    resolution = 5.0
    planning_animation(ox, oy, resolution)

does not produce complete coverage on my system settings.

**Expected behavior**

The coverage is not like in the animated gif shown:
https://github.com/AtsushiSakai/PythonRoboticsGifs/raw/master/PathPlanning/GridBasedSweepCPP/animation.gif

**Screenshots**
Check the following image:

![Figure_1](https://github.com/AtsushiSakai/PythonRobotics/assets/1160083/41b2d5c9-70e9-4d50-8192-1219028960ad)

**Desktop (please complete the following information):**
I used Python 3.10.13 on Linux (opensuse tumbleweed)
numpy                             1.25.2
matplotlib                        3.6.3
matplotlib-inline                 0.1.6
scipy                             1.11.1

Can you let me know which python and lib versions works for that example.

Thanks.

**Comment by UjjwalPardeshi** [comment]
can you assign me this please

**Comment by kk-1** [comment]
Further investigation suggests float2integer rounding issue.
Probably different Python/package versions have different precision defaults.

**Comment by AtsushiSakai** [comment]
The latest codes have still this issue? I merged this PR https://github.com/AtsushiSakai/PythonRobotics/pull/917

**Comment by kk-1** [comment]
Thanks it works now!
