### ISSUE TITLE
Fixing grid_based_sweep_coverage_path_planner.py

### ISSUE THREAD

**Issue by ssr-yuki** [AtsushiSakai/PythonRobotics#915]
Hi.

The current behavior of `PathPlanning/GridBasedSweepCPP/grid_based_sweep_coverage_path_planner.py` is different from one shown in the [doc](https://atsushisakai.github.io/PythonRobotics/modules/path_planning/coverage_path/coverage_path.html).

**Screenshots**

| current | expected (same as shown in the [doc](https://atsushisakai.github.io/PythonRobotics/modules/path_planning/coverage_path/coverage_path.html)) |
| :---: | :---: |
| ![Screenshot from 2023-10-04 20-07-01](https://github.com/AtsushiSakai/PythonRobotics/assets/15957608/4eb957ff-51d7-4ab1-accd-0b7ec7d520fa) | ![Screenshot from 2023-10-04 20-07-39](https://github.com/AtsushiSakai/PythonRobotics/assets/15957608/369e974c-d644-4b60-bf1a-8cdb48585c5a) |
| ![Screenshot from 2023-10-04 20-07-22](https://github.com/AtsushiSakai/PythonRobotics/assets/15957608/c7d15a11-e69f-4f2d-912c-cc9a05f6f6b0) | ![Screenshot from 2023-10-04 20-08-00](https://github.com/AtsushiSakai/PythonRobotics/assets/15957608/9820f130-1c80-44d3-824e-92b090b7cb5e) | 

**Cause**

Investigating [the change log](https://github.com/AtsushiSakai/PythonRobotics/commits/master/PathPlanning/GridBasedSweepCPP/grid_based_sweep_coverage_path_planner.py), I found that [the latest commit](https://github.com/AtsushiSakai/PythonRobotics/commit/0fc769421f66a6403f750781dc46534d84e7c424) caused this behavior change. 

![Screenshot from 2023-10-04 20-15-30](https://github.com/AtsushiSakai/PythonRobotics/assets/15957608/246b76c2-87ad-4ccc-91eb-8311987aa76c)

The change in L54-55->L53 of the file (also see the image) silently transformed the `occupied_val` argument of `check_occupied_from_xy_index` function from 1.0 into 0.5.

As a reference, the following modification for the current L53 can correct this issue temporally.

```python
-                 if self.check_occupied(next_c_x_index, next_c_y_index, grid_map):
---
+                 if grid_map.check_occupied_from_xy_index(next_c_x_index,
                                                           next_c_y_index, FloatGrid(1.0)):
```

Please check it. Thanks.

**Comment by MrDavidAlv** [comment]
good

**Comment by AtsushiSakai** [comment]
Thank you for great explanation about the issue.
