### ISSUE TITLE
Strange Animation Results in test_rrt_star_reeds_shepp.py

### ISSUE THREAD

**Issue by videh25** [AtsushiSakai/PythonRobotics#944]
### Bug
test3 in test_rrt_star_reeds_shepp.py tries to generate a path with step_size = 20. Since it is a test file, animation is kept off. However, on turning the animation on, the result is very  weird. RRT does not plan with smooth RS curves but rather with straight lines with sharp corners.

### Expected Behaviour
Also ran test2 from test_rrt_star_reeds_shepp.py (step_size = 0.2). They plan and generate smooth RS curves only. 
 
### Screenshots
**test3 Animation**
![Screenshot from 2023-12-01 17-02-51](https://github.com/AtsushiSakai/PythonRobotics/assets/66770479/6242cfc5-dc76-4100-b5bc-e9b158792ae9)

***test2 Animation***
![Screenshot from 2023-12-01 17-10-18](https://github.com/AtsushiSakai/PythonRobotics/assets/66770479/2f2f0dcd-7ee3-47bf-8d15-be3450dbc506)

### Desktop
 - Python 3.9.5
 - numpy 1.24.3
 - scipy 1.10.1
 - matplotlib 3.7.1
 - cvxpy 1.4.1
 - Ubuntu 20.04

**Comment by AtsushiSakai** [comment]
@videh25 Is it OK to close this issue by your PR?

**Comment by videh25** [comment]
Yes, sounds great!
