### ISSUE TITLE
ModuleNotFoundError: No module named 'utils'

### ISSUE THREAD

**Issue by rosrookie** [AtsushiSakai/PythonRobotics#966]
Hi, when I git clone the whole project. and installed all requirements. And when I run with mpc. error happends:

`ModuleNotFoundError: No module named 'utils'`

I do not change anything, just clone and run, then error happends.

**Comment by rosrookie** [comment]
well, it seems like I change the code order, then wroked.

before:
`
import matplotlib.pyplot as plt
import cvxpy
import math
import numpy as np
import sys
import pathlib
from utils.angle import angle_mod
sys.path.append(str(pathlib.Path(__file__).parent.parent.parent))

from PathPlanning.CubicSpline import cubic_spline_planner
`

after:
`
import matplotlib.pyplot as plt
import cvxpy
import math
import numpy as np
import sys
import pathlib
sys.path.append(str(pathlib.Path(__file__).parent.parent.parent))

from PathPlanning.CubicSpline import cubic_spline_planner
from utils.angle import angle_mod
`

**Comment by rosrookie** [comment]
it seems like when I change the order, then worked.

before:

```
import matplotlib.pyplot as plt
import cvxpy
import math
import numpy as np
import sys
import pathlib
from utils.angle import angle_mod
sys.path.append(str(pathlib.Path(__file__).parent.parent.parent))

from PathPlanning.CubicSpline import cubic_spline_planner
```

after:
```
import matplotlib.pyplot as plt
import cvxpy
import math
import numpy as np
import sys
import pathlib
sys.path.append(str(pathlib.Path(__file__).parent.parent.parent))

from PathPlanning.CubicSpline import cubic_spline_planner
from utils.angle import angle_mod
```

**Comment by ZhaiMen-Hub** [comment]
Find the same problem in lqr_speed_steer_control.py

**Comment by kamocat** [comment]
This seems to be a recurring issue:

- #709 
- #750 
- #754 

Either we should fix all the scripts as above, or update the "HOW TO USE" section with instructions to install the 'utils' module.
