### ISSUE TITLE
NDT grid_map init

### ISSUE THREAD

**Issue by xiao-ge4** [AtsushiSakai/PythonRobotics#991]
https://github.com/AtsushiSakai/PythonRobotics/blob/1656cab0d229d294ec151ec9d4cbe086b271e1cf/Mapping/ndt_map/ndt_map.py#L56
In your original code, you are calling `_create_grid_index_map` on lines 56-59 which uses grid_map, but you only create` self.grid_map` in the next step. This will cause an error.
You should move the initialization on line 62 above line 56 to avoid the error and achieve the intended functionality described in the documentation.

**Comment by AtsushiSakai** [comment]
PR is welcome.
