### ISSUE TITLE
Plot issue for in random_inverse_kinematics.py

### ISSUE THREAD

**Issue by Ombenavides** [AtsushiSakai/PythonRobotics#995]
**Describe the bug**
I am quite a noob at this kind of request so please forgive me if I make mistakes :)
I've been trying to run the file random_inverse_kinematics after installing everything and also importing the lib. But my code just plots blank. I cannot see anything. :( 

**Expected behavior**
I expected to get the plot for the random kinematics to explore the code

**Screenshots**
![Plot](https://github.com/AtsushiSakai/PythonRobotics/assets/148692663/a1b89f97-e355-4ed2-b40a-4e8bf210ed79)

**Desktop (please complete the following information):**
 - Python version 3.12.2
 - Each library version 
 - OS version Windows 11 home

Maybe I am committing a basic mistake. But please help me out with this issue. 
Thanks in advance.

**Comment by GiladRobee** [comment]
Not an expert either so take it with a grain of salt.
I found out NLinkArm is using mpl_toolkits which depend on old Matplotlib functions that were deprecated some versions ago.
try and use it in a Venv, docker with the right lib version (probably the ones from the requirement folder.

**Comment by AtsushiSakai** [comment]
@Ombenavides Hi. Thank you for reporting. I can reproduced the issue. PR #1007 should fix this issue. Please try it with the latest code.
